version: '3.6'

services:
  cbs:
    build: .
    image: jeffre/cbs:8.3.0.101
    hostname: portal.allinternet.com.au
    restart: on-failure
    volumes:
    #### Critical paths ####
    #  # config
      - /data/cbs/conf:/cbs/conf
      - /data/cbs/system:/cbs/system
    #  # logs
      - /data/cbs/logs:/cbs/logs
    #  # client data
      - /data/users:/cbs/users
    #  - ./users:/users
    #  #### Branding ####
    #  # OBC agent downloads
    #  - ./cbs/download:/cbs/download
    ports:
      - "80:80"
      - "443:443"
      - "9444-9464"
    environment:
      - TZ=${TZ}
      - CBS_MAC=00:1a:4d:4a:a9:a7
